services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /mnt/c/Users/Jakub/Pictures/.siril/data:/data
    environment:
      - HOME_DIR=/data
      - SIRIL_CLI=/usr/sbin/siril-cli
      - SECRET_KEY=your_super_secret_key_here

  stacker:
    build: .
    volumes:
      - /mnt/c/Users/Jakub/Pictures/.siril/data:/data
    environment:
      - HOME_DIR=/data
      - SIRIL_CLI=/usr/sbin/siril-cli
      - SECRET_KEY=your_super_secret_key_here
    command: >
      sh -c "while true; do
        echo 'Running stacker script...';
        python stacker.py;
        echo 'Stacker run complete. Sleeping for 60 seconds...';
        sleep 60;
      done"