FROM archlinux:base-devel

RUN pacman -Syu --noconfirm && \
	pacman -S --noconfirm git sudo base-devel python python-pip

RUN useradd -m builder && \
	echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder

USER builder
WORKDIR /home/builder
RUN git clone https://aur.archlinux.org/yay-bin.git && \
	cd yay-bin && \
	makepkg -si --noconfirm && \
	rm -rf /home/builder/yay-bin

RUN yay -S --noconfirm siril-git

USER root
RUN pacman -S --noconfirm --needed python-setuptools

RUN git clone https://gitlab.com/free-astro/pysiril.git /tmp/pysiril && \
	cd /tmp/pysiril && \
	python setup.py bdist_wheel && \
	pip install dist/pysiril-*.whl --break-system-packages && \
	rm -rf /tmp/pysiril

RUN useradd -m appuser
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt --break-system-packages

COPY --chown=appuser:appuser . .

USER appuser