services:
  web:
    build: .
    ports:
      - "${SERVER_PORT}:8000"
    volumes:
      - ${HOST_DATA_PATH}:/data
    environment:
      - HOME_DIR=/data
      - SIRIL_CLI=/usr/sbin/siril-cli
      - SECRET_KEY=${SECRET_KEY}

  stacker:
    build: .
    volumes:
      - ${HOST_DATA_PATH}:/data
    environment:
      - HOME_DIR=/data
      - SIRIL_CLI=/usr/sbin/siril-cli
      - SECRET_KEY=${SECRET_KEY}
    command: >
      sh -c "while true; do
        echo 'Running stacker script...';
        python stacker.py;
        echo 'Stacker run complete. Sleeping for ${STACKER_INTERVAL_S} seconds...';
        sleep ${STACKER_INTERVAL_S};
      done"