services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - ${HOST_DATA_PATH}:/data
      - ${HOST_LOG_PATH}:/logs
    environment:
      - HOME_DIR=/data
      - LOG_DIR=/logs
      - SECRET_KEY=${SECRET_KEY}

  stacker:
    build:
      context: .
      dockerfile: Dockerfile.stacker
    volumes:
      - ${HOST_DATA_PATH}:/data
      - ${HOST_LOG_PATH}:/logs
    environment:
      - HOME_DIR=/data
      - LOG_DIR=/logs
      - SIRIL_CLI=/usr/sbin/siril-cli
    command: >
      sh -c "while true; do
        echo 'Running stacker script...';
        python stacker.py;
        echo 'Stacker run complete. Sleeping for ${STACKER_INTERVAL_S} seconds...';
        sleep ${STACKER_INTERVAL_S};
      done"